# Generated by Django 2.1.7 on 2019-06-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('option', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('télephone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
