# Generated by Django 2.1.7 on 2019-06-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='image',
        ),
    ]
